---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
options(width = 120, digits = 2)
```

# histmatch

Provides a fast implementation for weighted [histogram matching](https://en.wikipedia.org/wiki/Histogram_matching).

```{r echo = FALSE}
devtools::load_all(quiet = TRUE)
library(dplyr, warn.conflicts = FALSE)
```

```{r}
histmatch(1:10, 1:10)
histmatch(1:10, 2:11)
histmatch(1:11, 5:6)
histmatch(1:11, c(2, 4, 5))
```


## Timing

For random vectors, which are generated using the following function:

```{r}
r <- function(e) runif(10 ** e)
```

```{r echo = FALSE}
set.seed(123)
microbenchmark::microbenchmark(
  r(4),
  histmatch(r(3), r(3)),
  histmatch(r(3), r(3), r(3)),
  histmatch(r(3), r(4)),
  histmatch(r(3), r(4), r(4)),
  histmatch(r(4), r(4)),
  histmatch(r(4), r(4), r(4)),
  histmatch(r(4), r(3)),
  histmatch(r(4), r(3), r(3)),
  times = 100
) %>%
  group_by(expr) %>% 
  summarize(median_ms = median(time) / 1e6) %>% 
  ungroup
```


## Installation

```r
devtools::install_github("krlmlr/histmatch")
```
